### ISSUE TITLE
ngOptions not working for angular version 1.4.3

### ISSUE THREAD

**Issue by srthakkar** [cletourneau/angular-bootstrap-datepicker#9]
Hello, I am using angular-bootstrap-datepicker with Angular js 1.4.3 but it's not working. It's working with Angular-1.0.8 as per this demo 
http://jsfiddle.net/cletourneau/kGGCZ/

-> With Angular 1.4.3 it's give error message like,
Error: [$compile:ctreq] Controller 'select', required by directive 'ngOptions', can't be found!
http://errors.angularjs.org/1.4.3/$compile/ctreq?p0=select&p1=ngOptions

And at the time of debugging i found that ngOption is undefined in bootstrap-datepicker js..

I exactly follow all the step from this http://jsfiddle.net/cletourneau/kGGCZ/ . just changed angular version.

**Comment by kyleiwaniec** [comment]
I am having the same issue. Any ideas?

**Comment by srthakkar** [comment]
Hi kyleiwaniec,

Use https://jqueryui.com/datepicker/ and https://github.com/angular-ui/ui-date
I used it and it's working fine. Use Ui date picker instead of  bootstrap-datepicker

**Comment by kyleiwaniec** [comment]
thanks @srthakkar - I also found ngDatepicker, and it is working fine, just needs some CSS love :)

**Comment by sovattha** [comment]
A hint on how to fix is to rename ngOptions to ngDatepickerOptions, then to use

```
<input ng-datepicker-options...>
```

But some others minor issues appear after this (conflicts with CSS) which is just the consequence of the plugin not being maintained anymore.
